/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mediacodecrtmp_RtmpNative */

#ifndef _Included_com_example_mediacodecrtmp_RtmpNative
#define _Included_com_example_mediacodecrtmp_RtmpNative
#ifdef __cplusplus
extern "C" {
#endif


int InitReceiveSockets();

void CleanuptReceiveSockets();
/*
 * Class:     com_example_mediacodecrtmp_RtmpNative
 * Method:    naTest
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_mediacodecrtmp_RtmpNative_naTest
  (JNIEnv *, jobject, jstring);

JNIEXPORT void JNICALL Java_com_example_mediacodecrtmp_RtmpNative_naStopThread
  (JNIEnv *, jobject);

static void* parseRtmpData(void *arg);

#ifdef __cplusplus
}
#endif
#endif
